base_model: Qwen/Qwen2.5-Math-7B-Instruct

load_in_8bit: false
load_in_4bit: false

datasets:
  - path: train_YS.jsonl
    type: chat_template

dataset_prepared_path: preprocess
val_set_size: 0.01
output_dir: ./outputs

adapter: 
lora_model_dir:

sequence_len: 16384
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_swiglu: true
liger_fused_linear_cross_entropy: true

wandb_project: KoR1-3
wandb_entity: 
wandb_watch:
wandb_name: qwen2.5-math-7b-YS
wandb_log_model:
hub_model_id: 

gradient_accumulation_steps: 64
micro_batch_size: 1
num_epochs: 5
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

gradient_checkpointing:
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_ratio: 0.05
weight_decay: 0.01
evals_per_epoch: 0
saves_per_epoch: 1

fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap:  Qwen2DecoderLayer
  fsdp_activation_checkpointing: true
